In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel(r'C:\Users\HP\Desktop\Job Business Analyst\Data Training.xlsx')
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 14 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Export Coaching Clinic ID & FTA             41 non-null     object
 1   Pengenalan Export A-Z bagi UKM Batch 1      275 non-null    object
 2   Pengenalan Export A-Z bagi UKM Batch 2      99 non-null     object
 3   Pengenalan Export A-Z bagi UKM Batch 3      83 non-null     object
 4   Seminar Online Fotografi                    107 non-null    object
 5   Seminar Online Fotografi Batch 2            60 non-null     object
 6   Pelatihan Pengenalan Ekspor ID & GEN        17 non-null     object
 7   Pelatihan Lanjutan Market Research          36 non-null     object
 8   Pelatihan Lanjutan Market Research Batch 2  169 non-null    object
 9   Basic Training Export                       6 non-null      object
 10  Training of Financial Export Management     24 non-null     object
 11  Pelatihan Paket 1                           11 non-null     object
 12  Pelatihan Paket 2                           12 non-null     object
 13  Teknik Negosiasi dan Kontrak Dagang         16 non-null     object
dtypes: object(14)
memory usage: 30.2+ KB

,Export Coaching Clinic ID & FTA,Pengenalan Export A-Z bagi UKM Batch 1,Pengenalan Export A-Z bagi UKM Batch 2,Pengenalan Export A-Z bagi UKM Batch 3,Seminar Online Fotografi,Seminar Online Fotografi Batch 2,Pelatihan Pengenalan Ekspor ID & GEN,Pelatihan Lanjutan Market Research,Pelatihan Lanjutan Market Research Batch 2,Basic Training Export,Training of Financial Export Management,Pelatihan Paket 1,Pelatihan Paket 2,Teknik Negosiasi dan Kontrak Dagang
0,Mia Widyastuty,Rosmawar,Gunawan Sjah,Galih Purnomo Putro,A.A. Ayu Sri Yuliani,Yeni Kusmiati,Burhanuddin,azis bakhtiar,Kusumawardani,M. Dakhri Sanusi,Viralea Hediana,Ana Rahaju,Cornelia Ferny Jansen,RETNO HARTATI
1,Widya Wijaya I,sulismiyatun,Yeni Kusmiati,Inawati,Achmad suherman,Vista puri cendhani,AWALUDDIN MUCHTAR,Novi Kurnia S,Evs,"Yosie Ermawan, SH. MH",Christian Widya Purnama,Anggita Hary Prasetyo,Setyo,Viralea Hediana
2,Christian Widya Purnama Setyabudi,Jaya,Christian Widya Purnama Setyabudi,Ifriyawani,Ade sri rahayu,wina dyah,Raden Daru Sulistiono,Evs,Ani Murdiati,Viralea Hediana,Helda Dewi Damayanti,Dicky Al-farizi Riswanto,Ana Rahaju Wibowo,NURHADI
3,Kemas Djauhari,Hanny Jessica Putri,Vista Puri Cendhani,Fatimah Yahya,Adi Irawanto,Anjar,Adji Widodo,Agnes Heratri,Ir. Ghoffar Abdul Wasik,Renny Puspitasari,Hayatun nuchus,Eko Sugiarto,Ema Herawati,"Roland Parlindungan,ST"
4,Erlina Dewinta Febriani,Siceli Wulandari,Teguh Hamanda,Yunita Ekawati,Adinegara,Dewi Anwar,"Susilowati, SH",Joko Tri S,henky surjono,Leonard Frans Ardianto,Eddy Subarkah,Fikri Ramadani,helda,Ratri Isnaeni Kurnia

In [3]:
des=data.describe()
Jumlah_Peserta=des.loc['unique']

In [4]:
bg=data['Pelatihan Paket 2']
bg.dropna()
bg=list(dict.fromkeys(bg))
len(bg)
Jumlah_Peserta

Export Coaching Clinic ID & FTA                41
Pengenalan Export A-Z bagi UKM Batch 1        257
Pengenalan Export A-Z bagi UKM Batch 2         99
Pengenalan Export A-Z bagi UKM Batch 3         82
Seminar Online Fotografi                      106
Seminar Online Fotografi Batch 2               60
Pelatihan Pengenalan Ekspor ID & GEN           17
Pelatihan Lanjutan Market Research             34
Pelatihan Lanjutan Market Research Batch 2    149
Basic Training Export                           6
Training of Financial Export Management        24
Pelatihan Paket 1                              11
Pelatihan Paket 2                              10
Teknik Negosiasi dan Kontrak Dagang            16
Name: unique, dtype: object

In [5]:
old=['Export Coaching Clinic ID & FTA',
     'Pengenalan Export A-Z bagi UKM Batch 1',
     'Pengenalan Export A-Z bagi UKM Batch 2',
     'Pengenalan Export A-Z bagi UKM Batch 3',
     'Seminar Online Fotografi',
     'Seminar Online Fotografi Batch 2',
     'Pelatihan Pengenalan Ekspor ID & GEN',
     'Pelatihan Lanjutan Market Research',
     'Pelatihan Lanjutan Market Research Batch 2']
new=['Basic Training Export',
     'Training of Financial Export Management',
     'Pelatihan Paket 1',
     'Pelatihan Paket 2',
     'Teknik Negosiasi dan Kontrak Dagang']
df=pd.DataFrame({new[0]:[0,0,0,0,0,0,0,0,0],
                 new[1]:[0,0,0,0,0,0,0,0,0],
                 new[2]:[0,0,0,0,0,0,0,0,0],
                 new[3]:[0,0,0,0,0,0,0,0,0],
                 new[4]:[0,0,0,0,0,0,0,0,0]})
df.index=old

In [6]:
for i in old:
    Data1=data[i].dropna()
    Data1=Data1.str.lower()
    Data1=list(dict.fromkeys(Data1))
    for j in new:
        k=0
        Data2=data[j].dropna()
        Data2=Data2.str.lower()
        Data2=list(dict.fromkeys(Data2))
        for ii in Data1:
            for jj in Data2:
                if ii==jj:
                    df[j][i]+=1
df

,Basic Training Export,Training of Financial Export Management,Pelatihan Paket 1,Pelatihan Paket 2,Teknik Negosiasi dan Kontrak Dagang
Export Coaching Clinic ID & FTA,0,0,0,0,0
Pengenalan Export A-Z bagi UKM Batch 1,0,7,1,0,0
Pengenalan Export A-Z bagi UKM Batch 2,0,3,0,0,1
Pengenalan Export A-Z bagi UKM Batch 3,0,1,1,0,0
Seminar Online Fotografi,0,5,1,0,1
Seminar Online Fotografi Batch 2,0,2,0,0,0
Pelatihan Pengenalan Ekspor ID & GEN,0,0,0,0,0
Pelatihan Lanjutan Market Research,0,2,1,0,0
Pelatihan Lanjutan Market Research Batch 2,1,8,2,0,1

In [36]:
data_old=data[old[0]].dropna()
data_old=data_old.str.lower()
data_old=list(dict.fromkeys(data_old))
old_1=old[1:]
for i in old_1:
    temp=data[i].dropna()
    temp=temp.str.lower()
    temp=list(dict.fromkeys(temp))
    for j in temp:
        data_old.append(j)
data_old=list(dict.fromkeys(data_old))
print(len(data_old))

data_new=data[new[0]].dropna()
data_new=data_new.str.lower()
data_new=list(dict.fromkeys(data_new))
new_1=new[1:]
for i in new_1:
    temp=data[i].dropna()
    temp=temp.str.lower()
    temp=list(dict.fromkeys(temp))
    for j in temp:
        data_new.append(j)
data_new=list(dict.fromkeys(data_new))
print(len(data_new))

578
62

In [37]:
kk=0
for i in data_old:
    for j in data_new:
        if i==j:
            kk+=1

16

In [40]:
print('Training tahun lalu memiliki',len(old),'pelatihan dengan total peserta',len(data_old),'. Dengan rata - rata peserta adalah',len(data_old)/len(old),'per pelatihan')
print('Training tahun ini memiliki',len(new),'pelatihan dengan total peserta',len(data_new),'. Dengan rata - rata peserta adalah',len(data_new)/len(new),'per pelatihan')
print('Terdapat',kk,'peserta training tahun lalu yang mengikuti training tahun ini')

Training tahun lalu memiliki 9 pelatihan dengan total peserta 578 . Dengan rata - rata peserta adalah 64.22222222222223 per pelatihan
Training tahun ini memiliki 5 pelatihan dengan total peserta 62 . Dengan rata - rata peserta adalah 12.4 per pelatihan
Terdapat 16 peserta training tahun lalu yang mengikuti training tahun ini

In [41]:
df

,Basic Training Export,Training of Financial Export Management,Pelatihan Paket 1,Pelatihan Paket 2,Teknik Negosiasi dan Kontrak Dagang
Export Coaching Clinic ID & FTA,0,0,0,0,0
Pengenalan Export A-Z bagi UKM Batch 1,0,7,1,0,0
Pengenalan Export A-Z bagi UKM Batch 2,0,3,0,0,1
Pengenalan Export A-Z bagi UKM Batch 3,0,1,1,0,0
Seminar Online Fotografi,0,5,1,0,1
Seminar Online Fotografi Batch 2,0,2,0,0,0
Pelatihan Pengenalan Ekspor ID & GEN,0,0,0,0,0
Pelatihan Lanjutan Market Research,0,2,1,0,0
Pelatihan Lanjutan Market Research Batch 2,1,8,2,0,1